"""Initial Migration

Revision ID: 41d25f9dec88
Revises: 366b41baae19
Create Date: 2019-02-28 15:43:00.770709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d25f9dec88'
down_revision = '366b41baae19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitches', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitches')
    # ### end Alembic commands ###
