"""postblog

Revision ID: 6a9021c7ab8f
Revises: dc1ed84055f8
Create Date: 2019-03-02 09:26:12.364469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9021c7ab8f'
down_revision = 'dc1ed84055f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Post_blog', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_blog')
    # ### end Alembic commands ###
