"""Initial Migration

Revision ID: b21d2a27ca40
Revises: 
Create Date: 2019-03-04 17:22:04.096393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21d2a27ca40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsription', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('subsription', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_constraint('subsription_user_id_fkey', 'subsription', type_='foreignkey')
    op.drop_column('subsription', 'user_id')
    op.drop_column('subsription', 'Post_blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsription', sa.Column('Post_blog', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subsription', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subsription_user_id_fkey', 'subsription', 'users', ['user_id'], ['id'])
    op.drop_column('subsription', 'name')
    op.drop_column('subsription', 'email')
    # ### end Alembic commands ###
