"""comments and sub

Revision ID: c758c6bbf285
Revises: 6a9021c7ab8f
Create Date: 2019-03-02 09:27:14.835565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c758c6bbf285'
down_revision = '6a9021c7ab8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subsription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Post_blog', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_blog_id'], ['post_blog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('subsription')
    # ### end Alembic commands ###
